### ISSUE TITLE
Is it still good to use?

### ISSUE THREAD

**Issue by eglerean** [HBClab/NuisanceRegression#1]
Thanks for these scripts, they are helpful!

This is not really an issue, I just wanted to ask if the code is still up to date and if you are still maintaining the project, or if there's "a better way" to do post-fmriprep nuisance regression.

Thanks!
Enrico

**Comment by jdkent** [comment]
Glad you found these useful! I do not recall anything being wrong with this repository per say, but depending on your goals, there are a couple options (you may find more preferable) post FMRIPREP. 

[xcpengine](http://xcpengine.readthedocs.io): process resting state data post FMRIPREP.

[fitlins](https://fitlins.readthedocs.io/en/latest/): process task data post FMRIPREP.

[Denoiser](https://github.com/arielletambini/denoiser): same in spirit as these scripts, but does a better job imo.

**Comment by eglerean** [comment]
Thanks so much! I am gathering the various post-fmriprep options for the users of our computational cluster. This is very helpful!!

Cheers
Enrico
